# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version=0.3.0
maven_group=com.minersmarket
archives_name=minersmarket

# Release properties (used by gradle/shared release tasks)
release_project_name=Miner's Market
modrinth_project_id=6sCy4MMM
curseforge_project_id=1457302

# Target Minecraft version
target_mc_version=1.21.1
